export const Notes = {
  Documents: '<h6>Documentación de acuerdo con lo establecido en el artículo 14 de la Resolución CREG 174 de 2021 o aquella que la modifique o sustituya:</h6>' +
             'i) Diagramas unifilares (usar una norma nacional o internacional), ii) documento con la identificación esquemática de la conexión del sistema de puesta a tierra con su conductor correspondiente y que contenga el esquema de protecciones con sus características, iii) documento con las distancias de seguridad respecto a las redes existentes y el cuadro de cargas de la demanda total.'+
             '<div class="mt-2"><h6>Para los tiempos de entrega asociados a la documentación listada arriba por favor referirse a la Nota 3 al final de este formulario</h6></div>',
  Conditions: '<h6>Para dispositivos o elementos que no estén cobijados por el RETIE, se requiere el Certificado de conformidad de producto bajo norma internacional o norma reconocida (ejemplo estándares UL 1741 o IEC 61727, como se presenta en el numeral 5 y 6). Para certificar esta información se tiene plazo hasta antes de entrar en operación, '+
              'conforme las reglas del RETIE y del artículo 14 de la Resolución CREG 174 de 2021.</h6>'+
              '<h6 class="mt-2">Cumplir con los requerimientos de protecciones definidos por el CNO en su Acuerdo 1522 de 2022 o aquel que lo modifique o sustituya, disponible en el siguiente vínculo:'+
              '<a target="_blank" href="https://www.cno.org.co/content/acuerdo-1522-por-el-cual-se-aprueban-los-requisitos-de-protecciones-para-la-conexion-de">'+
              'https://www.cno.org.co/content/acuerdo-1522-por-el-cual-se-aprueban-los-requisitos-de-protecciones-para-la-conexion-de</a><h6>',
  NoteOne: '<label> <h6>NOTA 1: </h6> Remitir formulario en formato Excel y PDF (firmado)  correspondiente del proyecto al correo electrónico XXXX@XXX.co con el siguiente asunto, y cargar la información al aplicativo de la página web del OR (hasta que la ventanilla única de la UPME esté habilitada):</label>',
  NoteTwo: '<h6>NOTA 2:</h6>Para proyectos que se conecten en el Nivel de tensión 1, adjuntar el archivo de la consulta de disponibilidad de punto de conexión de la página web del OR con los datos del punto solicitado. En nivel de tensión N2 o N3 no es necesario el anterior archivo de consulta.',
  NoteThree: '<h6>NOTA 3:</h6>'+
            '<p>3.1) Las solicitudes que no lleguen con la información indicada conforme la Resolución CREG 174 de 2021 o el formulario incompleto se les aplicaran las reglas de subsanación de que trata el Anexo 5 de la misma Resolución.</p>'+
            '<p>3.2) La información que se debe entregar con el formulario de conexión simplificado es la indicada en el Artículo 14 de la Resolución CREG 174 de 2021 conforme a la capacidad instalada o nominal, Tipo de recurso (AGPE, AGGE, GD) y lo dispuesto en el Anexo 5 de la misma Resolución en sus literales vi (paso 2) y vii (paso 1).</p>'+
            '<p>3.3) Cuando se trate de un recurso que aplica el ultimo citado literal (vii del Anexo 5), solo se debe entregar el formulario de conexión simplificado con el registro de información sin ningún otro documento anexo, esto para que le sea suministrada la información para continuar con el estudio de conexión simplificado. </p>'+
            '<p>3.4) Para todo lo anterior, el restante de información que se indique en la citada Resolución se cargara en el sistema en linea conforme los pasos definidos durante el proceso de conexión definido en el Anexo 5 y artículo 14 de la Resolución CREG 174 de 2021.</p>'
}
